FROM node:23-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .

ENV DATABASE_URL="postgresql://neondb_owner:npg_rqHfA9OoZI2X@ep-curly-band-a8qt1x9x-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"

# Use migrate deploy instead of dev
RUN npx prisma generate
RUN npx prisma migrate deploy

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
